<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1a9b92c1-8c77-427a-94fe-95aaff6fb049</testSuiteGuid>
   <testCaseLink>
      <guid>258a3f5d-fac7-4796-a5eb-9a56d38d9554</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/variable practice 1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cf8775c9-2dba-4498-ad00-f306e38168f9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/variables data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59cf41c4-146e-4cb7-ad52-54eb2268efb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1cac9e14-a4db-4e78-adf4-97b312086f38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf8775c9-2dba-4498-ad00-f306e38168f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>facility</value>
         <variableId>d9f3d567-c073-4c49-a31c-22dee6aceaeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf8775c9-2dba-4498-ad00-f306e38168f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Visit date</value>
         <variableId>b89df3ff-b420-44fc-b7bc-9c60d3b26bae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cf8775c9-2dba-4498-ad00-f306e38168f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>comment</value>
         <variableId>4c914ed6-8427-4bcd-96ae-98d9cf2183e9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
